# Based on Zed's One Light implementation
# One Light is released under the MIT License and Copyright (c) 2014 GitHub Inc.

# base00 - Default Background
# base01 - Lighter Background (Used for status bars, line number and folding marks)
# base02 - Selection Background
# base03 - Comments, Invisibles, Line Highlighting
# base04 - Dark Foreground (Used for status bars)
# base05 - Default Foreground, Caret, Delimiters, Operators
# base06 - Light Foreground (Not often used)
# base07 - Light Background (Not often used)
# base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
# base0A - Classes, Markup Bold, Search Text Background
# base0B - Strings, Inherited Class, Markup Code, Diff Inserted
# base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
# base0D - Functions, Methods, Attribute IDs, Headings
# base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
# base0F - Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

base00 = "#fafafa"
base01 = "#d0d4da"
base02 = "#acb2be"
base03 = "#878a98"
base04 = "#58585a"
base05 = "#242529"
base06 = "#363c46"
base07 = "#7e8086"
base08 = "#d3604f"
base09 = "#ad6e26"
base0A = "#c18401"
base0B = "#649f57"
base0C = "#3882b7"
base0D = "#5c78e2"
base0E = "#a449ab"
base0F = "#b1574b"

vcs_added = "#27a657"
vcs_modified = "#d3b020"
vcs_deleted = "#e06c76"
